### ISSUE TITLE
About function update_maze()

### ISSUE THREAD

**Issue by fatihbayir** [BitsRobocon/MicroMouse_2020#4]
Hi, sir.

Can you please explain a bit about update_maze() function in your code. I suppose If there is wall update wall, but you update when a wall is equal to zero? can you plase give detail about it?

`void update_maze()
{
    int temp = 0;
    for(int i = 0; i < MAZE_SIZE; i++)
    {
        for(int j = 0; j < MAZE_SIZE; j++)
        {
            if(!((i==GOAL_ROW)&&(j==GOAL_COLUMN)))
            {
                int min = -1;
                if(wall_maze[i][j][0]==0)
                {
                    if(min==-1)
                    {
                        min = goal_maze[i-1][j];
                    }
                    else
                    {
                        if(goal_maze[i-1][j]<min)
                        {
                            min = goal_maze[i-1][j];
                        }
                    }
                }
                if(wall_maze[i][j][1]==0)
                {
                    if(min==-1)
                    {
                        min = goal_maze[i][j-1];
                    }
                    else
                    {
                        if(goal_maze[i][j-1]<min)
                        {
                            min = goal_maze[i][j-1];
                        }
                    }
                }
                if(wall_maze[i][j][2]==0)
                {
                    if(min==-1)
                    {
                        min = goal_maze[i][j+1];
                    }
                    else
                    {
                        if(goal_maze[i][j+1]<min)
                        {
                            min = goal_maze[i][j+1];
                        }
                    }
                }
                if(wall_maze[i][j][3]==0)
                {
                    if(min==-1)
                    {
                        min = goal_maze[i+1][j];
                    }
                    else
                    {
                        if(goal_maze[i+1][j]<min)
                        {
                            min = goal_maze[i+1][j];
                        }
                    }
                }
                if(min!=-1)
                {
                    if(goal_maze[i][j] != (min+1))
                    {
                        goal_maze[i][j]=(min+1);
                        temp = 1;
                    }
                }
            }
        }
        if(temp == 1)
        {
            break;
        }
    }
    if(temp == 1)
    {
        update_maze();
    }
}`

**Comment by ashutoshshrm529** [comment]
Hi @fatihbayir , 
 
So the update_maze() function is meant to change the maze array using the floodfill algorithm making it the centerpiece of this code. 

It's main job is doing this - https://youtu.be/N9TkDgJNJso

Now the approach that was opted for here is merely brute force and we now have a better algorithm for it, which however cannot be disclosed since this is for competitions that we will be participating in. My suggestion to you would be to write your own code for the update_maze() function and make it efficient. 

Thank you, 
Ashutosh Sharma
